#!/bin/bash
set -ueo pipefail

#NOTE - temporarily remove ARM64 build until we can figure out a workaround for installer check

docker buildx build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             #--platform linux/amd64,linux/arm64 \
             --platform linux/amd64 \
             --push -t isaudits/veil .